### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by gurpal2000** [deadprogram/frankie#1]
Hi

im using sinatra 0.9.4 and frankie 0.3.1 with facebooker 1.0.56

i can't get the example to work. It simply exits. I had to make a modification to ignore the "mmangino-" prefix for the gem in frankie.rb.

Is there a specific version combo i need or can we make it work with the above?

thanks

**Comment by tuupola** [comment]
Same problem here.

**Comment by ehq** [comment]
Same here.
